### ISSUE TITLE
generated app.css and app.js isn't minified

### ISSUE THREAD

**Issue by praveenpuglia** [praveenpuglia/exercism.io#1]

**Comment by praveenpuglia** [comment]
I think the project should point for css and js from **frontend/dist** directory instead of the **frontend/generated** directory. **dist** contains both `app.css` and `app.js` minified.

**Comment by praveenpuglia** [comment]
The files are indeed getting minified but not getting copied automatically into public directory. 

For now, manually adding updating the files does the job. Should we close this and have another issue/milestone stating the upgrade of front-end build system?

**Comment by hashd** [comment]
Created another issue with respect to the automation of copying minified files. Closing this.
