### ISSUE TITLE
Minified app.css and app.js isn't copied into the appropriate directory in the build process

### ISSUE THREAD

**Issue by hashd** [praveenpuglia/exercism.io#10]

**Comment by praveenpuglia** [comment]
will be changing this during the front-end revamp.

**Comment by praveenpuglia** [comment]
scss compilation is done. Gulp can now generate the required styles for current hootcode version wtih all the overrides. 

This also gives us a chance of removing much of the duplicate CSS which is introduced by loading both **app.css** and **application.css**. new file size would be `174KB` which is now `561KB` on the live site...

**Comment by praveenpuglia** [comment]
The gulp setup is complete and available in new-frontend-build-system branch. It'll soon be merged with upstream master.
