### ISSUE TITLE
replace the exercism favicon with a new hootcode one ?

### ISSUE THREAD

**Issue by praveenpuglia** [praveenpuglia/exercism.io#14]

**Comment by praveenpuglia** [comment]
put the new favicon in c972d7c 
@hashd  - looks decent?

![hootcode-favicon](https://cloud.githubusercontent.com/assets/313363/7879559/05066cdc-060f-11e5-9ea5-f54cdda6e330.png)

**Comment by hashd** [comment]
Hoot Hoot!
