### ISSUE TITLE
selectors are too specific and way too long

### ISSUE THREAD

**Issue by praveenpuglia** [praveenpuglia/exercism.io#2]
For example `bootstrapoverride.css` has these kind of rules.

```
#navbar ul li ul li a {
    color:black;
}
#navbar ul li ul li a:hover {
    background-color:#ce6b05;
}
```

**Comment by hashd** [comment]
Lets notify the dev team about this in the next meet

**Comment by praveenpuglia** [comment]
bad overrides are almost removed. I'll also be moving things from _overrides.scss to their respective locations in sections, components and more. Closing the issue here and will have a new issue specifying that.
